### PR TITLE
Merge branch 'main' of https://github.com/datkat21/pluto-web-os

### PR DESCRIPTION
**Pull request by bddylol**
same size, and fix icons

### CODE REVIEW

**Comment by buddy-codes** [comment]
oh & zoom in DevEnv

**Comment by buddy-codes** [comment]
this ALSO impl's terminal

**Comment by datkat21** [comment]
LGTM, but please reformat with Prettier with trailing commas to keep the code style consistent (or I’ll just do it)

**Comment by datkat21** [comment]
I'll do it after merging.

**Pull request merged**
